### ISSUE TITLE
Implement mov [DESTINATION], !x

### ISSUE THREAD

**Issue by qbalsdon** [adafruit/Adafruit_CircuitPython_PIOASM#15]
I would like to request the implementation of 

```
mov [DESTINATION], !x
```

I would offer to do this myself but I actually have a) no idea what !x means (at least in this context) and b) don't know how to add to this repo (domain knowledge of the code)

**Comment by tannewt** [comment]
Looks like it should work if you put a space inbetween `! x`. The move parsing code is here: https://github.com/adafruit/Adafruit_CircuitPython_PIOASM/blob/main/adafruit_pioasm.py#L141-L147

To support `!x` you'd need to test to see if the source starts with `!`, `~` or `::` and split accordingly.

**Comment by kevinjwalters** [comment]
FYI from https://learn.adafruit.com/intro-to-rp2040-pio-with-circuitpython#faq-3084251 under `mov operator restrictions` it says:

> The official dialect allows "!" to mean the same as "~". This is not accepted by adafruit_pioasm.

**Comment by gamblor21** [comment]
Fixed in #17 if it still causes issues please let me know.
