### ISSUE TITLE
mov with decrement on scratch reg gives unexpected result

### ISSUE THREAD

**Issue by MartinBaadsgaard** [adafruit/Adafruit_CircuitPython_PIOASM#38]
```
import rp2pio
import adafruit_pioasm


testpio = """
.program test
    pull; Pull from FIFO to OSR
    out y 32; OSR to Y
    jmp y-- next; Jump a line down, this is just done to test y--
next:  
    mov isr y; back from y to ISR
    push; Push ISR to FIFO
"""

assembled = adafruit_pioasm.assemble(testpio)
sm = rp2pio.StateMachine(
    assembled,
    frequency=2000,
)

inint = 255
initarr = int(inint).to_bytes(2, 'big', signed=False)
print(initarr)
sm.write(initarr)
inbuffer = bytearray(2)
sm.readinto(inbuffer)
print(inbuffer)
```

The 'jmp y-- next' line should decrement the Y register by one.
Behaviour is the following printed in the console:

`b'\x00\xff'
bytearray(b'\xff\xff')`

Expected output in console:

b'\x00\xff'
bytearray(b'\x00\xfe')

Replicating the code in MicroPython shows the expected behaviour.
MicroPython code:

```
from machine import Pin
from rp2 import PIO, StateMachine, asm_pio
from time import sleep

@asm_pio(sideset_init=PIO.OUT_LOW)
def pwm_prog():
    pull()
    out(y, 32)
    jmp(y_dec, "next")
    label("next")
    mov(isr, y)
    push()

class PIOPWM:
    def __init__(self, sm_id, pin, max_count, count_freq):
        self._sm = StateMachine(sm_id, pwm_prog, freq=2 * count_freq, sideset_base=Pin(pin))
        # Use exec() to load max count into ISR
        self._sm.put(max_count)
        self._sm.active(1)
        self._max_count = max_count

    def set(self, value):
        # Minimum value is -1 (completely turn off), 0 actually still produces narrow pulse
        value = max(value, -1)
        value = min(value, self._max_count)
        self._sm.put(value)

inval = 255
print(inval.to_bytes(2, 'big'))
pwm = PIOPWM(0, 25, max_count=inval, count_freq=10_000_000)
print(pwm._sm.get().to_bytes(2, 'big'))
```

Naively printing the result of the assembler gives:
CircuitPython ` array('H', [32928, 24640, 131, 41154, 32800]) `
MicroPython ` [array('H', [32928, 24640, 131, 41154, 32800]), 27, -1, 1073758208, 0, None, None, 2] `
So the actual instruction code seems identical between the two.

**Comment by tannewt** [comment]
Are you expecting 8 bit writes into the PIO FIFO? I'm not sure what MP does but CP will do writes that match the width of the input array. bytearrays will be 8 bits. `array` can be used to specify data of different sizes: https://docs.python.org/3/library/array.html This should definitely be documented better.

I think you'll be queueing up `0x00000000` which then becomes `0xffffffff`. `0xff` loads `0xffffffff` which probably becomes `0xfffffffe` but then the conversion from 32 bits to 8 takes the top 8 instead of the bottom 8.

**Comment by MartinBaadsgaard** [comment]
I expected the data to be read in as a whole block, filling in as much as possible of a 32bit word, yes.
Didn't expect it was on a per-element basis.
I have verified the behaviour is correct when using array.array. Closing ticket.

**Comment by tannewt** [comment]
I've filed an issue for adding the ability to write the FIFO when no code is running on the StateMachine: https://github.com/adafruit/circuitpython/issues/6019
