### ISSUE TITLE
TypeError: first_out_pin must be of type Pin, not CywPin

### ISSUE THREAD

**Issue by onetoucheddy** [adafruit/Adafruit_CircuitPython_PIOASM#54]
code doesnot work on a pico W. Is there an alternative for first_out_pin?
Code:
```py
assembled = adafruit_pioasm.assemble(hello)

sm = rp2pio.StateMachine(
    assembled,
    frequency=2000,
    first_out_pin=board.LED,
)
```

**Comment by tannewt** [comment]
The Pico W has the LED on a pin from the wifi module. For this demo you'll need to attach another LED to the pico w and provide that pin.
